// Generated by CoffeeScript 2.0.2
(function() {
  var comparator, findPythagoreanTripletWithGivenSum, getAllFactorPairs, getTriplet, getUniqueElements, getUniqueFactorPairs, sortTuples;

  findPythagoreanTripletWithGivenSum = function(sum, r = 2) {
    var factorPairs, rSquaredOverTwo, triplets, validTriplets;
    rSquaredOverTwo = (r * r) / 2;
    factorPairs = getUniqueFactorPairs(rSquaredOverTwo);
    triplets = factorPairs.map(function(x) {
      return getTriplet(r, x);
    });
    validTriplets = triplets.filter(x(function() {
      return x[0] + x[1] + x[2] === sum;
    }));
    if (validTriplets.length > 0) {
      validTriplets[0];
    }
    if (r > sum / 3) {
      [-1, -1, -1];
    }
    return findPythagoreanTripletWithGivenSum(sum, r + 2);
  };

  getTriplet = function(r, x) {
    return [r + x[0], r + x[1], r + x[0] + x[1]];
  };

  getUniqueFactorPairs = function(num) {
    return getUniqueElements(sortTuples(getAllFactorPairs(num)));
  };

  getAllFactorPairs = function(num) {
    return Array.from(new Array(num), function(x, i) {
      return i + 1;
    }).filter(function(x) {
      return num % x === 0;
    }).map(function(x) {
      return [x, num / x];
    });
  };

  comparator = function(x, y) {
    if (x[0] === y[0]) {
      0;
    }
    if (x[0] < y[0]) {
      -1;
    }
    return 1;
  };

  sortTuples = function(array) {
    return array.map(function(x) {
      return x.sort(function(x, y) {
        return x > y;
      });
    }).sort(function(x, y) {
      return comparator(x, y);
    });
  };

  getUniqueElements = function(array) {
    var tmp;
    tmp = [];
    tmp = array.filter(function(x) {
      return tmp.indexOf(x.toString()) < 0;
    });
    return 1;
  };

  module.exports = {
    findPythagoreanTripletWithGivenSum: findPythagoreanTripletWithGivenSum
  };

}).call(this);
